AWSTemplateFormatVersion: '2010-09-09'
Description: AWS CloudFormation template to deploy trivia game backend websocket api with respective integrations

Resources:
  # Lambda Functions
  TriviaConnect:
    Type: 'AWS::Lambda::Function'
    Properties:
      Handler: index.handler
      FunctionName: 'TriviaConnect'
      Role: !Sub 'arn:aws:iam::${AWS::AccountId}:role/LabRole'
      Code:
        ZipFile: |
          exports.handler = async (event) => {
            const response = {
              statusCode: 200,
              body: JSON.stringify('Websocket connected.'),
            };
            return response;
          };
      Runtime: nodejs20.x
      Timeout: 3
      MemorySize: 128

  TriviaDisconnect:
    Type: 'AWS::Lambda::Function'
    Properties:
      Handler: index.handler
      FunctionName: 'TriviaDisconnect'
      Role: !Sub 'arn:aws:iam::${AWS::AccountId}:role/LabRole'
      Code:
        ZipFile: |
          exports.handler = async (event) => {
            const response = {
              statusCode: 200,
              body: JSON.stringify('Hello from Lambda!'),
            };
            return response;
          };
      Runtime: nodejs20.x
      Timeout: 3
      MemorySize: 128

  TriviaStartGame:
    Type: 'AWS::Lambda::Function'
    Properties:
      Handler: index.handler
      FunctionName: 'TriviaStartGame'
      Role: !Sub 'arn:aws:iam::${AWS::AccountId}:role/LabRole'
      Code:
        ZipFile: |
          const { ApiGatewayManagementApiClient, PostToConnectionCommand} = require("@aws-sdk/client-apigatewaymanagementapi");
          const client = new ApiGatewayManagementApiClient({ endpoint: process.env.CONNECTION_URL });
            
          exports.handler = async (event) => {
            const connectionId = event.requestContext.connectionId;
            const message = new PostToConnectionCommand({ ConnectionId: connectionId, Data: "Game started" });
            await client.send(message);

            const response = { statusCode: 200 };
            return response;
          };
      Runtime: nodejs20.x
      Timeout: 3
      MemorySize: 128
      Environment:
        Variables:
          CONNECTION_URL: !Sub 'https://${TriviaWebsocketApi}.execute-api.${AWS::Region}.amazonaws.com/production'

  TriviaSubmitAnswer:
    Type: 'AWS::Lambda::Function'
    Properties:
      Handler: index.handler
      FunctionName: 'TriviaSubmitAnswer'
      Role: !Sub 'arn:aws:iam::${AWS::AccountId}:role/LabRole'
      Code:
        ZipFile: |
          exports.handler = async (event) => {
            const response = {
              statusCode: 200,
              body: JSON.stringify('Hello from Lambda!'),
            };
            return response;
          };
      Runtime: nodejs20.x
      Timeout: 3
      MemorySize: 128

  # Lambda Invocation Permissions
  ConnectPermission:
    Type: AWS::Lambda::Permission
    DependsOn:
      - TriviaWebsocketApi
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref TriviaConnect
      Principal: apigateway.amazonaws.com

  DisconnectPermission:
    Type: AWS::Lambda::Permission
    DependsOn:
      - TriviaWebsocketApi
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref TriviaDisconnect
      Principal: apigateway.amazonaws.com

  StartGamePermission:
    Type: AWS::Lambda::Permission
    DependsOn:
      - TriviaWebsocketApi
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref TriviaStartGame
      Principal: apigateway.amazonaws.com

  SubmitAnswerPermission:
    Type: AWS::Lambda::Permission
    DependsOn:
      - TriviaWebsocketApi
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref TriviaSubmitAnswer
      Principal: apigateway.amazonaws.com

  # Trivia WebSocket API
  TriviaWebsocketApi:
    Type: 'AWS::ApiGatewayV2::Api'
    Properties:
      Name: TriviaWebsocketApi
      ProtocolType: WEBSOCKET
      RouteSelectionExpression: '$request.body.action'

  # Deployment
  Deployment:
    Type: AWS::ApiGatewayV2::Deployment
    DependsOn:
      - ConnectRoute
      - DisconnectRoute
      - StartGameRoute
      - SubmitAnswerRoute
    Properties:
      ApiId: !Ref TriviaWebsocketApi

  # Stages
  ApiStage:
    Type: 'AWS::ApiGatewayV2::Stage'
    Properties:
      ApiId: !Ref TriviaWebsocketApi
      StageName: production
      DeploymentId: !Ref Deployment

  # WebSocket Routes
  ConnectRoute:
    Type: 'AWS::ApiGatewayV2::Route'
    Properties:
      ApiId: !Ref TriviaWebsocketApi
      RouteKey: '$connect'
      AuthorizationType: NONE
      Target: !Join
        - '/'
        -
          - 'integrations'
          - !Ref ConnectIntegration

  DisconnectRoute:
    Type: 'AWS::ApiGatewayV2::Route'
    Properties:
      ApiId: !Ref TriviaWebsocketApi
      RouteKey: '$disconnect'
      AuthorizationType: NONE
      Target: !Join
        - '/'
        -
          - 'integrations'
          - !Ref DisconnectIntegration

  StartGameRoute:
    Type: 'AWS::ApiGatewayV2::Route'
    Properties:
      ApiId: !Ref TriviaWebsocketApi
      RouteKey: 'startGame'
      AuthorizationType: NONE
      Target: !Join
        - '/'
        -
          - 'integrations'
          - !Ref StartGameIntegration

  SubmitAnswerRoute:
    Type: 'AWS::ApiGatewayV2::Route'
    Properties:
      ApiId: !Ref TriviaWebsocketApi
      RouteKey: 'submitAnswer'
      AuthorizationType: NONE
      Target: !Join
        - '/'
        - 
          - 'integrations'
          - !Ref SubmitAnswerIntegration

  # Integrations
  ConnectIntegration:
    Type: 'AWS::ApiGatewayV2::Integration'
    Properties:
      ApiId: !Ref TriviaWebsocketApi
      IntegrationType: AWS_PROXY
      IntegrationUri: !Sub 'arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${TriviaConnect.Arn}/invocations'

  DisconnectIntegration:
    Type: 'AWS::ApiGatewayV2::Integration'
    Properties:
      ApiId: !Ref TriviaWebsocketApi
      IntegrationType: AWS_PROXY
      IntegrationUri: !Sub 'arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${TriviaDisconnect.Arn}/invocations'

  StartGameIntegration:
    Type: 'AWS::ApiGatewayV2::Integration'
    Properties:
      ApiId: !Ref TriviaWebsocketApi
      IntegrationType: AWS_PROXY
      IntegrationUri: !Sub 'arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${TriviaStartGame.Arn}/invocations'

  SubmitAnswerIntegration:
    Type: 'AWS::ApiGatewayV2::Integration'
    Properties:
      ApiId: !Ref TriviaWebsocketApi
      IntegrationType: AWS_PROXY
      IntegrationUri: !Sub 'arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${TriviaSubmitAnswer.Arn}/invocations'
